stages:
  split:
    cmd: python src/data/split_data.py
    deps:
    - data/raw
    - src/data/split_data.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
  normalize:
    cmd: python src/data/normalize_data.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - src/data/normalize_data.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/xgb_best_params.pkl
  training:
    cmd: python src/models/train_model.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - models/xgb_best_params.pkl
    - src/models/train_model.py
    outs:
    - models/xgb_trained_model.pkl
  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/xgb_trained_model.pkl
    - src/models/evaluate_model.py
    outs:
    - data/predictions/prediction.csv
    metrics:
    - metrics/score.json:
        cache: false
